; M5Stick jaune (original) — atelier sensibilisation cybersécurité
; Carte : ESP32-PICO-D4, écran ST7735

[env:m5stick]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default.csv
lib_deps =
    m5stack/M5Unified@^0.2.2
    m5stack/M5GFX@^0.2.2
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_M5STICK_ORIGINAL=1
